const fs   = require("fs");
const path = require("path");

// ── 1. Create mailer.js ──────────────────────────────────────────────────────
const mailerLines = [];
mailerLines.push('const nodemailer = require("nodemailer");');
mailerLines.push('');
mailerLines.push('const transporter = nodemailer.createTransport({');
mailerLines.push('  service: "gmail",');
mailerLines.push('  auth: {');
mailerLines.push('    user: process.env.EMAIL_USER,');
mailerLines.push('    pass: process.env.EMAIL_PASS,');
mailerLines.push('  },');
mailerLines.push('});');
mailerLines.push('');
mailerLines.push('async function sendAlertEmail(toEmail, alertData) {');
mailerLines.push('  const { symbol, condition, targetPrice, triggeredPrice } = alertData;');
mailerLines.push('');
mailerLines.push('  const subject = "STOCKIX Alert: " + symbol + " has " + (condition === "below" ? "dropped below" : "risen above") + " $" + targetPrice;');
mailerLines.push('');
mailerLines.push('  const html = [');
mailerLines.push('    "<div style=\'font-family:sans-serif;max-width:480px;margin:0 auto;background:#0d0d0d;color:#fff;border-radius:12px;overflow:hidden\'>",');
mailerLines.push('    "  <div style=\'background:#111;padding:24px 28px;border-bottom:1px solid rgba(255,255,255,0.08)\'>",');
mailerLines.push('    "    <span style=\'font-size:18px;font-weight:700;letter-spacing:2px\'>STOCKIX</span>",');
mailerLines.push('    "  </div>",');
mailerLines.push('    "  <div style=\'padding:28px\'>",');
mailerLines.push('    "    <h2 style=\'margin:0 0 8px;font-size:20px\'>Price Alert Triggered</h2>",');
mailerLines.push('    "    <p style=\'color:rgba(255,255,255,0.5);margin:0 0 24px;font-size:14px\'>Your alert condition has been met</p>",');
mailerLines.push('    "    <div style=\'background:rgba(255,255,255,0.05);border-radius:10px;padding:20px;margin-bottom:20px\'>",');
mailerLines.push('    "      <div style=\'font-size:28px;font-weight:800;margin-bottom:4px\'>" + symbol + "</div>",');
mailerLines.push('    "      <div style=\'font-size:14px;color:rgba(255,255,255,0.5);margin-bottom:16px\'>Stock Symbol</div>",');
mailerLines.push('    "      <div style=\'display:flex;gap:16px\'>",');
mailerLines.push('    "        <div>",');
mailerLines.push('    "          <div style=\'font-size:11px;color:rgba(255,255,255,0.4);margin-bottom:4px\'>CONDITION</div>",');
mailerLines.push('    "          <div style=\'font-size:15px;font-weight:600;color:" + (condition === "below" ? "#f87171" : "#4ade80") + "\'>" + (condition === "below" ? "Below" : "Above") + " $" + targetPrice + "</div>",');
mailerLines.push('    "        </div>",');
mailerLines.push('    "        <div>",');
mailerLines.push('    "          <div style=\'font-size:11px;color:rgba(255,255,255,0.4);margin-bottom:4px\'>TRIGGERED AT</div>",');
mailerLines.push('    "          <div style=\'font-size:15px;font-weight:600;color:#fff\'>$" + Number(triggeredPrice).toFixed(2) + "</div>",');
mailerLines.push('    "        </div>",');
mailerLines.push('    "        <div>",');
mailerLines.push('    "          <div style=\'font-size:11px;color:rgba(255,255,255,0.4);margin-bottom:4px\'>TIME</div>",');
mailerLines.push('    "          <div style=\'font-size:15px;font-weight:600;color:#fff\'>" + new Date().toLocaleString() + "</div>",');
mailerLines.push('    "        </div>",');
mailerLines.push('    "      </div>",');
mailerLines.push('    "    </div>",');
mailerLines.push('    "    <a href=\'http://localhost:3000/dashboard\' style=\'display:inline-block;background:#4ade80;color:#0d0d0d;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:700;font-size:14px\'>View Dashboard</a>",');
mailerLines.push('    "  </div>",');
mailerLines.push('    "  <div style=\'padding:16px 28px;border-top:1px solid rgba(255,255,255,0.06);font-size:12px;color:rgba(255,255,255,0.3)\'>",');
mailerLines.push('    "    This alert has been automatically deactivated. Log in to set a new one.",');
mailerLines.push('    "  </div>",');
mailerLines.push('    "</div>",');
mailerLines.push('  ].join("");');
mailerLines.push('');
mailerLines.push('  await transporter.sendMail({');
mailerLines.push('    from: "STOCKIX <" + process.env.EMAIL_USER + ">",');
mailerLines.push('    to: toEmail,');
mailerLines.push('    subject,');
mailerLines.push('    html,');
mailerLines.push('  });');
mailerLines.push('');
mailerLines.push('  console.log("[Mailer] Email sent to " + toEmail + " for " + symbol);');
mailerLines.push('}');
mailerLines.push('');
mailerLines.push('module.exports = { sendAlertEmail };');

fs.writeFileSync(path.join("src", "utils", "mailer.js"), mailerLines.join("\n"));
console.log("Created: src/utils/mailer.js");

// ── 2. Update alertChecker.js to send email ──────────────────────────────────
const checkerLines = [];
checkerLines.push('const cron  = require("node-cron");');
checkerLines.push('const Alert = require("../models/Alert");');
checkerLines.push('const User  = require("../models/User");');
checkerLines.push('const { getQuote } = require("./dataSource");');
checkerLines.push('const { sendAlertEmail } = require("./mailer");');
checkerLines.push('');
checkerLines.push('function startAlertChecker() {');
checkerLines.push('  cron.schedule("*/5 * * * *", async function() {');
checkerLines.push('    try {');
checkerLines.push('      var activeAlerts = await Alert.find({ isActive: true });');
checkerLines.push('      if (activeAlerts.length === 0) return;');
checkerLines.push('');
checkerLines.push('      console.log("[AlertChecker] Checking " + activeAlerts.length + " active alert(s)...");');
checkerLines.push('');
checkerLines.push('      for (var i = 0; i < activeAlerts.length; i++) {');
checkerLines.push('        var alert = activeAlerts[i];');
checkerLines.push('        try {');
checkerLines.push('          var quote = await getQuote(alert.symbol);');
checkerLines.push('          var livePrice = quote.c;');
checkerLines.push('          if (!livePrice) continue;');
checkerLines.push('');
checkerLines.push('          var triggered = false;');
checkerLines.push('          if (alert.condition === "below" && livePrice < alert.targetPrice) triggered = true;');
checkerLines.push('          if (alert.condition === "above" && livePrice > alert.targetPrice) triggered = true;');
checkerLines.push('');
checkerLines.push('          if (triggered) {');
checkerLines.push('            alert.isTriggered    = true;');
checkerLines.push('            alert.isActive       = false;');
checkerLines.push('            alert.triggeredPrice = livePrice;');
checkerLines.push('            alert.triggeredAt    = new Date();');
checkerLines.push('            await alert.save();');
checkerLines.push('');
checkerLines.push('            console.log("[AlertChecker] TRIGGERED: " + alert.symbol + " is " + livePrice);');
checkerLines.push('');
checkerLines.push('            // Send email to the user');
checkerLines.push('            try {');
checkerLines.push('              var user = await User.findById(alert.userId).select("email");');
checkerLines.push('              if (user && user.email) {');
checkerLines.push('                await sendAlertEmail(user.email, {');
checkerLines.push('                  symbol:         alert.symbol,');
checkerLines.push('                  condition:      alert.condition,');
checkerLines.push('                  targetPrice:    alert.targetPrice,');
checkerLines.push('                  triggeredPrice: livePrice,');
checkerLines.push('                });');
checkerLines.push('              }');
checkerLines.push('            } catch (emailErr) {');
checkerLines.push('              console.error("[AlertChecker] Email failed:", emailErr.message);');
checkerLines.push('            }');
checkerLines.push('');
checkerLines.push('          } else {');
checkerLines.push('            console.log("[AlertChecker] " + alert.symbol + " is " + livePrice + " -- not triggered yet");');
checkerLines.push('          }');
checkerLines.push('');
checkerLines.push('        } catch (err) {');
checkerLines.push('          console.error("[AlertChecker] Failed to check " + alert.symbol + ":", err.message);');
checkerLines.push('        }');
checkerLines.push('      }');
checkerLines.push('');
checkerLines.push('    } catch (err) {');
checkerLines.push('      console.error("[AlertChecker] Job failed:", err.message);');
checkerLines.push('    }');
checkerLines.push('  });');
checkerLines.push('');
checkerLines.push('  console.log("[AlertChecker] Started -- checking every 5 minutes");');
checkerLines.push('}');
checkerLines.push('');
checkerLines.push('module.exports = startAlertChecker;');

fs.writeFileSync(path.join("src", "utils", "alertChecker.js"), checkerLines.join("\n"));
console.log("Updated: src/utils/alertChecker.js");

console.log("");
console.log("Done! Restart your backend server to apply changes.");