const fs   = require("fs");
const path = require("path");

// ── Fix 1: User test — remove address test (field doesn't exist in schema) ───
const userTests = [
  '// User Model — Unit Tests',
  'const mongoose = require("mongoose");',
  'const User     = require("../models/User");',
  '',
  'beforeAll(async () => { await mongoose.connect("mongodb://127.0.0.1/test_users"); });',
  'afterAll(async () => { await mongoose.connection.dropDatabase(); await mongoose.disconnect(); });',
  'afterEach(async () => { await User.deleteMany({}); });',
  '',
  'describe("User Model — valid data", () => {',
  '',
  '  test("should save a valid user", async () => {',
  '    const user = new User({ name: "Ram Sharma", email: "ram@test.com", password: "password123" });',
  '    const saved = await user.save();',
  '    expect(saved._id).toBeDefined();',
  '    expect(saved.name).toBe("Ram Sharma");',
  '    expect(saved.email).toBe("ram@test.com");',
  '    expect(saved.role).toBe("user");',
  '    expect(saved.isActive).toBe(true);',
  '  });',
  '',
  '  test("should hash the password before saving", async () => {',
  '    const user = new User({ name: "Ram", email: "ram2@test.com", password: "password123" });',
  '    await user.save();',
  '    expect(user.password).not.toBe("password123");',
  '    expect(user.password.startsWith("$2")).toBe(true);',
  '  });',
  '',
  '  test("comparePassword should return true for correct password", async () => {',
  '    const user = new User({ name: "Ram", email: "ram3@test.com", password: "password123" });',
  '    await user.save();',
  '    const match = await user.comparePassword("password123");',
  '    expect(match).toBe(true);',
  '  });',
  '',
  '  test("comparePassword should return false for wrong password", async () => {',
  '    const user = new User({ name: "Ram", email: "ram4@test.com", password: "password123" });',
  '    await user.save();',
  '    const match = await user.comparePassword("wrongpassword");',
  '    expect(match).toBe(false);',
  '  });',
  '',
  '  test("toJSON should not include password", async () => {',
  '    const user = new User({ name: "Ram", email: "ram5@test.com", password: "password123" });',
  '    await user.save();',
  '    const json = user.toJSON();',
  '    expect(json.password).toBeUndefined();',
  '    expect(json.name).toBe("Ram");',
  '  });',
  '',
  '  test("should store email in lowercase", async () => {',
  '    const user = new User({ name: "Ram", email: "RAM@TEST.COM", password: "password123" });',
  '    await user.save();',
  '    expect(user.email).toBe("ram@test.com");',
  '  });',
  '',
  '  test("should default role to user", async () => {',
  '    const user = new User({ name: "Ram", email: "ram7@test.com", password: "password123" });',
  '    await user.save();',
  '    expect(user.role).toBe("user");',
  '  });',
  '',
  '  test("should allow role to be set to admin", async () => {',
  '    const user = new User({ name: "Admin", email: "admin@test.com", password: "password123", role: "admin" });',
  '    await user.save();',
  '    expect(user.role).toBe("admin");',
  '  });',
  '',
  '});',
  '',
  'describe("User Model — invalid data", () => {',
  '',
  '  test("should reject user with no name", async () => {',
  '    const user = new User({ email: "test@test.com", password: "password123" });',
  '    await expect(user.save()).rejects.toThrow();',
  '  });',
  '',
  '  test("should reject user with no email", async () => {',
  '    const user = new User({ name: "Ram", password: "password123" });',
  '    await expect(user.save()).rejects.toThrow();',
  '  });',
  '',
  '  test("should reject duplicate email", async () => {',
  '    await User.create({ name: "Ram", email: "duplicate@test.com", password: "password123" });',
  '    const user2 = new User({ name: "Shyam", email: "duplicate@test.com", password: "password456" });',
  '    await expect(user2.save()).rejects.toThrow();',
  '  });',
  '',
  '  test("should reject role that is not user or admin", async () => {',
  '    const user = new User({ name: "Ram", email: "ram8@test.com", password: "password123", role: "superuser" });',
  '    await expect(user.save()).rejects.toThrow();',
  '  });',
  '',
  '});',
].join("\n");

// ── Fix 2: Portfolio — userId is String with default, not required ────────────
const portfolioTests = [
  '// Portfolio Model — Unit Tests',
  'const mongoose  = require("mongoose");',
  'const Portfolio = require("../models/Portfolio");',
  '',
  'beforeAll(async () => { await mongoose.connect("mongodb://127.0.0.1/test_portfolio"); });',
  'afterAll(async () => { await mongoose.connection.dropDatabase(); await mongoose.disconnect(); });',
  'afterEach(async () => { await Portfolio.deleteMany({}); });',
  '',
  'describe("Portfolio Model — valid data", () => {',
  '',
  '  test("should save a portfolio with one position", async () => {',
  '    const portfolio = new Portfolio({',
  '      userId: "user123",',
  '      positions: [{ symbol: "AAPL", quantity: 10, avgCost: 150 }],',
  '    });',
  '    const saved = await portfolio.save();',
  '    expect(saved.positions.length).toBe(1);',
  '    expect(saved.positions[0].symbol).toBe("AAPL");',
  '    expect(saved.positions[0].quantity).toBe(10);',
  '    expect(saved.positions[0].avgCost).toBe(150);',
  '  });',
  '',
  '  test("should save a portfolio with multiple positions", async () => {',
  '    const portfolio = new Portfolio({',
  '      userId: "user123",',
  '      positions: [',
  '        { symbol: "AAPL", quantity: 10, avgCost: 150 },',
  '        { symbol: "TSLA", quantity: 5,  avgCost: 200 },',
  '        { symbol: "NVDA", quantity: 2,  avgCost: 500 },',
  '      ],',
  '    });',
  '    const saved = await portfolio.save();',
  '    expect(saved.positions.length).toBe(3);',
  '  });',
  '',
  '  test("should uppercase the symbol automatically", async () => {',
  '    const portfolio = new Portfolio({',
  '      userId: "user123",',
  '      positions: [{ symbol: "aapl", quantity: 10, avgCost: 150 }],',
  '    });',
  '    const saved = await portfolio.save();',
  '    expect(saved.positions[0].symbol).toBe("AAPL");',
  '  });',
  '',
  '  test("should default sector to Other", async () => {',
  '    const portfolio = new Portfolio({',
  '      userId: "user123",',
  '      positions: [{ symbol: "AAPL", quantity: 10, avgCost: 150 }],',
  '    });',
  '    const saved = await portfolio.save();',
  '    expect(saved.positions[0].sector).toBe("Other");',
  '  });',
  '',
  '  test("should allow adding a position later", async () => {',
  '    const portfolio = await Portfolio.create({',
  '      userId: "user123",',
  '      positions: [{ symbol: "AAPL", quantity: 10, avgCost: 150 }],',
  '    });',
  '    portfolio.positions.push({ symbol: "TSLA", quantity: 5, avgCost: 200 });',
  '    await portfolio.save();',
  '    const updated = await Portfolio.findById(portfolio._id);',
  '    expect(updated.positions.length).toBe(2);',
  '  });',
  '',
  '  test("should allow removing a position", async () => {',
  '    const portfolio = await Portfolio.create({',
  '      userId: "user123",',
  '      positions: [',
  '        { symbol: "AAPL", quantity: 10, avgCost: 150 },',
  '        { symbol: "TSLA", quantity: 5,  avgCost: 200 },',
  '      ],',
  '    });',
  '    portfolio.positions = portfolio.positions.filter(p => p.symbol !== "AAPL");',
  '    await portfolio.save();',
  '    const updated = await Portfolio.findById(portfolio._id);',
  '    expect(updated.positions.length).toBe(1);',
  '    expect(updated.positions[0].symbol).toBe("TSLA");',
  '  });',
  '',
  '});',
  '',
  'describe("Portfolio Model — invalid data", () => {',
  '',
  '  test("should reject position with no symbol", async () => {',
  '    const portfolio = new Portfolio({',
  '      userId: "user123",',
  '      positions: [{ quantity: 10, avgCost: 150 }],  // missing symbol',
  '    });',
  '    await expect(portfolio.save()).rejects.toThrow();',
  '  });',
  '',
  '  test("should reject position with no quantity", async () => {',
  '    const portfolio = new Portfolio({',
  '      userId: "user123",',
  '      positions: [{ symbol: "AAPL", avgCost: 150 }],  // missing quantity',
  '    });',
  '    await expect(portfolio.save()).rejects.toThrow();',
  '  });',
  '',
  '});',
].join("\n");

// ── Fix 3: Watchlist — userId is String with default, not required ────────────
const watchlistTests = [
  '// Watchlist Model — Unit Tests',
  'const mongoose  = require("mongoose");',
  'const Watchlist = require("../models/Watchlist");',
  '',
  'beforeAll(async () => { await mongoose.connect("mongodb://127.0.0.1/test_watchlist"); });',
  'afterAll(async () => { await mongoose.connection.dropDatabase(); await mongoose.disconnect(); });',
  'afterEach(async () => { await Watchlist.deleteMany({}); });',
  '',
  'describe("Watchlist Model — valid data", () => {',
  '',
  '  test("should save a watchlist with one item", async () => {',
  '    const wl = new Watchlist({',
  '      userId: "user123",',
  '      items:  [{ symbol: "AAPL", name: "Apple Inc." }],',
  '    });',
  '    const saved = await wl.save();',
  '    expect(saved.items.length).toBe(1);',
  '    expect(saved.items[0].symbol).toBe("AAPL");',
  '  });',
  '',
  '  test("should save multiple watchlist items", async () => {',
  '    const wl = new Watchlist({',
  '      userId: "user123",',
  '      items: [{ symbol: "AAPL" }, { symbol: "TSLA" }, { symbol: "NVDA" }],',
  '    });',
  '    const saved = await wl.save();',
  '    expect(saved.items.length).toBe(3);',
  '  });',
  '',
  '  test("should uppercase symbol automatically", async () => {',
  '    const wl = new Watchlist({',
  '      userId: "user123",',
  '      items: [{ symbol: "aapl" }],',
  '    });',
  '    const saved = await wl.save();',
  '    expect(saved.items[0].symbol).toBe("AAPL");',
  '  });',
  '',
  '  test("should save optional note on item", async () => {',
  '    const wl = new Watchlist({',
  '      userId: "user123",',
  '      items: [{ symbol: "AAPL", notes: "watching for breakout" }],',
  '    });',
  '    const saved = await wl.save();',
  '    expect(saved.items[0].notes).toBe("watching for breakout");',
  '  });',
  '',
  '  test("should allow adding item to existing watchlist", async () => {',
  '    const wl = await Watchlist.create({',
  '      userId: "user123",',
  '      items: [{ symbol: "AAPL" }],',
  '    });',
  '    wl.items.push({ symbol: "TSLA" });',
  '    await wl.save();',
  '    const updated = await Watchlist.findById(wl._id);',
  '    expect(updated.items.length).toBe(2);',
  '  });',
  '',
  '  test("should allow removing item from watchlist", async () => {',
  '    const wl = await Watchlist.create({',
  '      userId: "user123",',
  '      items: [{ symbol: "AAPL" }, { symbol: "TSLA" }],',
  '    });',
  '    wl.items = wl.items.filter(i => i.symbol !== "AAPL");',
  '    await wl.save();',
  '    const updated = await Watchlist.findById(wl._id);',
  '    expect(updated.items.length).toBe(1);',
  '    expect(updated.items[0].symbol).toBe("TSLA");',
  '  });',
  '',
  '});',
  '',
  'describe("Watchlist Model — invalid data", () => {',
  '',
  '  test("should reject item with no symbol", async () => {',
  '    const wl = new Watchlist({',
  '      userId: "user123",',
  '      items: [{ name: "Apple" }],  // missing symbol',
  '    });',
  '    await expect(wl.save()).rejects.toThrow();',
  '  });',
  '',
  '});',
].join("\n");

// ── Write all fixed test files ────────────────────────────────────────────────
fs.writeFileSync(path.join("src", "__tests__", "user.model.test.js"),      userTests);
console.log("Fixed: src/__tests__/user.model.test.js      (12 tests)");

fs.writeFileSync(path.join("src", "__tests__", "portfolio.model.test.js"), portfolioTests);
console.log("Fixed: src/__tests__/portfolio.model.test.js  (8 tests)");

fs.writeFileSync(path.join("src", "__tests__", "watchlist.model.test.js"), watchlistTests);
console.log("Fixed: src/__tests__/watchlist.model.test.js  (7 tests)");

console.log("");
console.log("Total: 10 + 12 + 8 + 7 = 37 tests");
console.log("Run with: npm test");